name: "Deploy Surge"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Build the website
      #   run: <commands_to_build_the_site_and_store_the_output_in_'./build'>
      - name: Deploy Surge
        uses: yg/deploy-surge@v1.0.0
        with:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
